#!/usr/bin/php
<?php

// Define file names and paths.
$css_variables   = "variables.php";
$css_style_sheet = "style.css";
$php_style_sheet = "style.php.css";



// Include "css variables" from file and define
// any other variables we may need.
include $css_variables;
$date = date("l, j M Y H:i:s T");

// Evaluate the contents of our "php style sheet"
// and store it in a variable.
$php_contents = file_get_contents("style.php.css")
	or die("Can't open $php_style_sheet.");
eval("\$php_contents = \"$php_contents\";");	

// Add some info to the top of style.css.
$php_contents =
"/* 
 * Do not edit this file directly!!!
 * Instead, put your code into $php_style_sheet,
 * then run ./css.php from the command line.
 *
 * Generated by css.php from $php_style_sheet
 * on $date.
 *
 **********************************************/
" . $php_contents; 


// Overwrite the contents of our old style sheet
// with the newly generated content.
$css_handle = fopen($css_style_sheet, 'w')
	or die("Can't open $css_style_sheet.");
fwrite($css_handle, $php_contents);
fclose($css_handle);

?>
